#SIG7 is a big simp.
name: Mac OS Build
on:
  push:
jobs:
  build:
    name: Mac OS Build
    runs-on: macos-latest
    steps:
      - name: Pulling the new commit
        uses: actions/checkout@v2
      - name: Setting up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      - name: Restore existing build cache for faster compilation
        uses: actions/cache@v3
        with:
          # wha?
          key: cache-build-mac
          path: |
            .haxelib/
            export/release/macos/haxe/
            export/release/macos/obj/
          restore-keys: |
            cache-build-mac
      - name: Installing/Updating libraries
        run: |
          haxelib install lime 7.9.0
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxe -cp ./update -D analyzer-optimize -main Update --interp
      - name: Building the game
        run: |
          haxelib run lime build mac
      - name: Uploading artifact (entire build)
        uses: actions/upload-artifact@v2
        with:
          name: 3Star2022
          path: export/release/macos/bin
      - name: Uploading artifact (executable)
        uses: actions/upload-artifact@v2
        with:
          name: Update-Mac
          path: export/release/macos/bin/3Star2022
      - name: Clearing already existing cache
        uses: actions/github-script@v6
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key == "cache-build-mac") {
                console.log('Clearing ' + cache.key + '...')
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
                console.log("Cache cleared.")
              }
            }
      - name: Uploading new cache
        uses: actions/cache@v3
        with:
          # Code taken from a different HaxeFlixel game thing, not sure why it does this.
          key: cache-build-mac
          path: |
            .haxelib/
            export/release/macos/haxe/
            export/release/macos/obj/
          restore-keys: |
            cache-build-mac
